Fix DirectX11 example in iframeworkview.md (#1302)
* Update iframeworkview.md

Need to use `make` method to instantiate `App` otherwise you get `error C2259: 'App': cannot instantiate abstract class`

* Edit

I know it's not syntactically necessary, but I like to make it clear that *make* is part of the C++/WinRT library.

Co-authored-by: Steven White <stwhi@microsoft.com>